name: gitsplit
on:
  push:
    tags:
      - '*'
  release:
    types: [ published ]

jobs:
  gitsplit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone https://github.com/Spomky-Labs/web-push /home/runner/work/spomky-labs/web-push && cd /home/runner/work/spomky-labs/web-push
      - name: Split repositories
        run: docker run --rm -t -e GH_TOKEN -v /cache/gitsplit:/cache/gitsplit -v /home/runner/work/spomky-labs/web-push:/srv jderusse/gitsplit gitsplit
        env:
          GH_TOKEN: ${{ secrets.GITSPLIT_TOKEN }}
